Add Arch Linux support
voxpupuli/puppet_metadata pull request #15
Opened 2020-12-19 18:59 UTC by bastelfreak

2020-12-21 12:56 UTC, ekohl commented
This is blocked on getting beaker, beaker-puppet and beaker-hostgenerator releases out. https://github.com/voxpupuli/beaker-hostgenerator/pull/191#issuecomment-748941723 has a good overview of what's needed. After that, :+1:

2021-12-05 12:39 UTC, ekohl commented on lib/puppet_metadata/metadata.rb
> +      return true if ['Gentoo', 'Archlinux'].include? operatingsystem
This should already be covered by `releases.nil?` on the last line. Is this because you mock the value elsewhere?

2021-12-05 12:50 UTC, ekohl commented on lib/puppet_metadata/github_actions.rb
> +        real_releases = ['Gentoo', 'Archlinux'].include?(os) ? ['rolling'] : releases
I'd like to avoid the duplication between here and the other 2 places. I'm not sure what the best place to capture it, but it feels like this should be captured in the metadata somehow.

2021-12-05 13:39 UTC, bastelfreak commented on lib/puppet_metadata/metadata.rb
> +      return true if ['Gentoo', 'Archlinux'].include? operatingsystem
I was able to get rid of that line

2021-12-05 13:42 UTC, bastelfreak commented on lib/puppet_metadata/github_actions.rb
> +        real_releases = ['Gentoo', 'Archlinux'].include?(os) ? ['rolling'] : releases
The code is now working . What do you think is the best to do deduplication? we could hack `lib/puppet_metadata.rb` and set the release to rolling for Arch Linux and Gentoo. But that could confuse people if they assume the metadata object is 1:1 what's in the metadata.json

2021-12-05 13:50 UTC, bastelfreak commented
I'm testing this:
* https://github.com/voxpupuli/puppet-nginx/pull/1492
* https://github.com/voxpupuli/puppet-borg/pull/90

2022-02-11 15:28 UTC, bastelfreak commented
@ekohl can you take a look here again as well?

2022-02-12 21:05 UTC, ekohl requested changes
Could you perhaps add some tests. I'd have expected it to fail here:
https://github.com/voxpupuli/puppet_metadata/blob/3977d9432ad9f73388b993f35db96ae7de0879b5/spec/metadata_spec.rb#L184
Looks like that ensures certain values are yielded, but not that nothing else is yielded.

2022-02-12 21:05 UTC, ekohl commented on lib/puppet_metadata/github_actions.rb
> +            next unless AIO.has_aio_build?(os, release, puppet_version[:value]) || os == 'Archlinux' && puppet_version[:value] == puppet_major_versions.map{|h| h[:value]}.sort.reverse.first
While it doesn't make a huge difference, it's better to do `puppet_major_versions.map{|h| h[:value]}.sort.reverse.first` outside of the loop. `puppet_major_versions` doesn't change within it and that makes it a bit more efficient. It can also be more readable if you assign it a variable because right now it's quite a long line.

Also, I think braces around `os == 'Archlinux' && ...` is clearer.

However, that does make me wonder if we should change the implementation to roughly thing:

```ruby
metadata.operatingsystems.each_with_object([]) do |(os, releases), matrix_include|
  case os
  when 'Archlinux', 'Gentoo'
    setfile = PuppetMetadata::Beaker.os_release_to_setfile(os, 'rolling', use_fqdn: use_fqdn, pidfile_workaround: pidfile_workaround)
    if setfile
      puppet_version = puppet_major_versions.max_by { |version| version[:value] }[:value]
      matrix_include << construct_matrix_include(setfile, puppet_version)
    end
  else
    releases.each do |release|
      # Pretty much the current code but use construct_matrix_include
    end
  end
end
```

2022-02-13 10:59 UTC, bastelfreak commented on lib/puppet_metadata/github_actions.rb
> +            next unless AIO.has_aio_build?(os, release, puppet_version[:value]) || os == 'Archlinux' && puppet_version[:value] == puppet_major_versions.map{|h| h[:value]}.sort.reverse.first
I will have a look at your suggestion later again. for now I created two methods in the metadata class to provide the lowest/highest puppet versions. They are quite short but could be useful for others as well. I just tested it in https://github.com/voxpupuli/puppet-borg/pull/90/checks and it's working as expected.

2022-02-13 12:25 UTC, bastelfreak commented on lib/puppet_metadata/github_actions.rb
> +            next unless AIO.has_aio_build?(os, release, puppet_version[:value]) || os == 'Archlinux' && puppet_version[:value] == puppet_major_versions.map{|h| h[:value]}.sort.reverse.first
I implemented the method. The generated matrix works but the Arch Linux name is now a bit odd:
![2022-02-13-132411_465x403_scrot](https://user-images.githubusercontent.com/341866/153752917-08fc150e-e5d1-4978-955f-22526ddcc979.png)

2022-02-15 10:13 UTC, closed without merging