Implement rubocop
voxpupuli/puppet_metadata pull request #50
Opened 2022-06-23 08:43 UTC by bastelfreak

2022-06-23 08:43 UTC, bastelfreak commented
@ekohl if you want to have rubocop here I can proceed and fix the violations

2022-06-23 08:47 UTC, ekohl reviewed
:+1: on adding Rubocop.

2022-06-23 08:47 UTC, ekohl commented on puppet_metadata.gemspec
> +  s.required_ruby_version = '>= 2.4.0'
I'd prefer an upper bound `< 4`

2022-06-23 08:47 UTC, ekohl commented on .github/workflows/test.yml
>    test:
You could make this depend on the rubocop step so you don't run tests unless Rubocop passes.

2022-06-23 09:05 UTC, bastelfreak commented on puppet_metadata.gemspec
> +  s.required_ruby_version = '>= 2.4.0'
added the upper bound. I set 2.4.0 as lowest version because that's what currently CI runs on.

2022-06-23 09:05 UTC, ekohl commented on .github/workflows/test.yml
>    test:
The test suite in this module is fast (< 15 seconds for a full run) so I guess it's fine.

2022-06-23 09:42 UTC, ekohl requested changes

2022-06-23 09:42 UTC, ekohl commented on .rubocop_todo.yml
> +# This configuration was generated by
I'd like to avoid a large TODO file. Any reason we can't get these resolved?

2022-06-23 09:42 UTC, ekohl commented on lib/puppet_metadata/beaker.rb
> +        '7' => 'centos:7.6.1810'
Can we set the style to keep trailing commas instead?

2022-06-23 10:07 UTC, bastelfreak commented on .rubocop_todo.yml
> +# This configuration was generated by
available time limits this :D 
Fixing some of them would be a breaking change (like renaming methods) or take a lot of time (like max black/class length). I think this is still a good improvement because it will at least lint new code and prevent the codebase from getting worse.

2022-06-23 10:07 UTC, bastelfreak commented on .github/workflows/test.yml
>    test:
updated it

2023-07-04 15:22 UTC, ekohl commented on lib/puppet_metadata/github_actions.rb
> +              yield [os, release, puppet_version] if AIO.has_aio_build?(os, release, puppet_version[:value])
I think we should disable the guard cop here because we also disable the line length cop, in which case the guard cop is bad (IMHO). This very long line is hard to parse mentally.

2023-07-04 15:22 UTC, ekohl commented on .rubocop_todo.yml
> +Gemspec/RequiredRubyVersion:
I think this was solved. Perhaps the TODO file needs to be generated?

2023-07-05 07:00 UTC, bastelfreak commented on .rubocop_todo.yml
> +Gemspec/RequiredRubyVersion:
done

2023-07-05 07:03 UTC, bastelfreak commented on lib/puppet_metadata/github_actions.rb
> +              yield [os, release, puppet_version] if AIO.has_aio_build?(os, release, puppet_version[:value])
done

2023-07-05 07:11 UTC, merged