Puppet 8: Run unit tests on Ruby 3.2
voxpupuli/puppet_metadata pull request #75
Opened 2023-04-25 20:46 UTC by bastelfreak

2023-04-25 20:47 UTC, vchepkov approved these changes

2023-04-25 20:57 UTC, natemccurdy approved these changes

2023-04-26 02:22 UTC, natemccurdy approved these changes

2023-04-26 17:37 UTC, ekohl requested changes
Could you also add Fedora 36 to the list? Other than that :+1:

2023-04-26 17:37 UTC, ekohl commented on lib/puppet_metadata/aio.rb
>          '7' => 5..7,
Looks like there are also EL7 builds @ https://yum.puppet.com/puppet8/el/index.html
```suggestion
        '7' => 5..8,
```

2023-04-26 20:09 UTC, merged